### PR TITLE
Fix Freertos SysTick frequency

### LINKED ISSUE #4: vTaskDelay() shorter as expected
Hi
I try to use vTaskDelay() inside the thread loop and I note that the delay is shorter than I expected. 
All FreeRTOS configs are default (as was defined in Cascoda-SDK). The MCU clock is 48000000

I connect the logic analyzer and fetch the data from gpio. And the period between pin toggling was around 250ms
vTaskDelay(pdMS_TO_TICKS(1000));
I try to adjust configTICK_RATE_HZ but it didn't give a positive result.

The second thing is in cascoda_wait.c have a function WAIT_ms() which is also used in RTOS examples. 
This function blocks RTOS context switching. I believe this function should take into account using OS or bare-metal
I replace BSP_WaitTicks() with vTaskDelay() and my project start to work smother. At liest, the logs start to prints when I expect them.
Thank's

### PR DESCRIPTION
**Pull request by CiaranWoodward**
Also includes bundled codesize improvements.

The issue reported in #4 was due to the system frequency changing after the SysTick was configured. This fix automatically reconfigures the SysTick hardware whenever the system frequency is modified.

Resolves #4

### CODE REVIEW

File: baremetal/platform/cascoda-nuvoton-chili2/port/source/cascoda_chili_secure.c [hunk 1]
```diff
@@ -146,8 +147,32 @@ static const IP_T ip_tbl[] = {
 };
 #endif
 
+static uint32_t CHILI_FreqEnumToInt(fsys_mhz aFreqEnum)
```
Comment (taraskornuta) [inline baremetal/platform/cascoda-nuvoton-chili2/port/source/cascoda_chili_secure.c]: I have a small suggestion for improvement. You can get rid of this function by modifying the enum:
`/****** Enum system core clock frequency [MHz] ******/
typedef enum fsys_mhz
{
	FSYS_4MHZ  = 4000000,
	FSYS_12MHZ = 12000000,
	FSYS_16MHZ = 16000000,
	FSYS_24MHZ = 24000000,
	FSYS_32MHZ = 32000000,
	FSYS_48MHZ = 48000000,
	FSYS_64MHZ = 64000000
} fsys_mhz;`

If I'm not mistaken... But it will increase the memory footprint

Comment (CiaranWoodward) [reply baremetal/platform/cascoda-nuvoton-chili2/port/source/cascoda_chili_secure.c]: Good suggestion, applied in b0ed64f. I scaled the numbers to MHz so it still fits in a uint8_t. Doesn't affect ram and saves 12 bytes of code 🎉

Comment (taraskornuta) [reply baremetal/platform/cascoda-nuvoton-chili2/port/source/cascoda_chili_secure.c]: I checked all works fine. I guess we can close this issue))
